### ISSUE TITLE
Migrate all components to postgres storage for wallets

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/von#96]
Migrate all components containing wallets to postgres backed wallet storage.

**Environments:**

**TheOrgBook-BC (`bc-tob`):**
- [x] Dev
- [x] Test
- [x] Prod
- [x] Prod-tmp

**Ontario's Verifiable Organizations (`ont-tob`)**
- [x] Dev
- [x] Test
- [x] Prod

**Verifiable Organizations Network (`demo-tob`)**
- [x] Dev
- [x] Test

**BC Registries Agent:**
- [x] Dev
- [x] Test
- [x] Prod
- [x] Prod-tmp

**Ontario Registries Agent:**
- [x] Dev
- [x] Test
- [x] Prod

**Environments to update:**
- [x] devex-bcgov-dac-dev
- [x] devex-bcgov-dap-dev
- [x] devex-von-bc-registries-agent-dev
- [x] devex-von-bc-registries-agent-prod
- [x] devex-von-bc-registries-agent-test
- [x] devex-von-bc-tob-dev
- [x] devex-von-bc-tob-prod
- [x] devex-von-bc-tob-test
- [x] ontvon-von-dev
- [x] ontvon-von-ont-registries-agent-dev
- [x] ontvon-von-ont-registries-agent-prod
- [x] ontvon-von-ont-registries-agent-test
- [x] ontvon-von-prod
- [x] ontvon-von-test

**Comment by WadeBarnes** [comment]
For the agents wallet config will look something like this;
```
    wallet:
      seed: $WALLET_SEED_BCREG
      type: postgres
      params:
        storage_config:
          url: "$POSTGRESQL_WALLET_HOST:$POSTGRESQL_WALLET_PORT"
      access_creds:
        key: $WALLET_ENCRYPTION_KEY
        storage_credentials:
          account: $POSTGRESQL_WALLET_USER
          password: $POSTGRESQL_WALLET_PASSWORD
        key_derivation_method: ARGON2I_MOD
```

Requires the `1.6-ew(-3)` image(s).
